use ТМРKarle_UNIVER

--1-- список кафедр, их факультетов, если этот факультет осущ. подготовку технологов
SELECT  PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME 
		FROM PULPIT,FACULTY, PROFESSION  
WHERE PULPIT.FACULTY = FACULTY.FACULTY and
PROFESSION.PROFESSION_NAME In (SELECT PROFESSION_NAME FROM PROFESSION  
        WHERE (PROFESSION_NAME Like '%технология%') or (PROFESSION_NAME like '%технологии%'))  

--2-- то же самое, но с inner join
SELECT  PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME 
		FROM PROFESSION, PULPIT inner join FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY 
WHERE PROFESSION.PROFESSION_NAME In (SELECT PROFESSION_NAME FROM PROFESSION  
WHERE (PROFESSION_NAME Like '%технология%') or (PROFESSION_NAME like '%технологии%'))  

--3-- то же самое, но без подзапроса 
SELECT  PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME 
		FROM PULPIT inner join FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION 
ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE (PROFESSION_NAME Like '%технология%') or (PROFESSION_NAME like '%технологии%')

--4-- самая вместительная аудитория каждого типа,завис
SELECT  AUDITORIUM_TYPE, AUDITORIUM_CAPACITY 
		FROM AUDITORIUM A
WHERE A.AUDITORIUM = (SELECT  TOP(1) AUDITORIUM FROM AUDITORIUM B 
WHERE A.AUDITORIUM_TYPE = B.AUDITORIUM_TYPE
ORDER BY AUDITORIUM_CAPACITY DESC)

--5-- список факультетов, на которых нет ни одной кафедры 
SELECT FACULTY.FACULTY_NAME FROM FACULTY	
WHERE Not EXISTS (SELECT * FROM PULPIT
WHERE FACULTY.FACULTY = PULPIT.FACULTY)

SELECT * FROM PULPIT;

--6-- строка, содержащая средние значения оценок по оаип, бд и субд
SELECT TOP 1 
	  (SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'ОАиП' ) [ОАиП],
	  (SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'БД' ) [БД], 
	  (SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'СУБД') [СУБД] 
  FROM PROGRESS 

--7-- ALL - список всех самых вместительных аудиторий ,завис
SELECT * FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY>=ALL(SELECT AUDITORIUM.AUDITORIUM_CAPACITY FROM AUDITORIUM 
WHERE AUDITORIUM.AUDITORIUM LIKE '%2%') 

--8-- ANY - список всех аудиторий, кроме самых маленьких (15 мест),завис
SELECT * FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY>ANY(SELECT AUDITORIUM.AUDITORIUM_CAPACITY FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM LIKE '%2%')
